language: r

r_packages:
 - VGAM

bioc_packages:
 - Rsamtools
 - GenomicRanges
 - IRanges
 - Biostrings
 - VGAM
 - VariantAnnotation
 
before_install:
 - R -e 'chooseCRANmirror(ind=75); install.packages("devtools"); BiocInstaller::biocLite("zlibbioc"); devtools::install_url("http://master.bioconductor.org/packages/devel/bioc/src/contrib/Rhtslib_0.99.18.tar.gz")'
    

